### ISSUE TITLE
Revisar campos de respuesta de los endpoints para tener en cuenta en caso de que no existan

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos_db_api#149]
De acuerdo al issue #148 se podría presentar el mismo caso con campos que no existan en un documento de las colecciones pero que hagan parte de la lógica de los mismos. Verificar que los condicionales tengan en cuenta la no existencia de estos campos y no sólo que puedan tener valor null.

**Comment by erikasv** [comment]
En la revisión no se encontraron campos que se estén usando como requeridos pero que no lo sean. Sin embargo, se listan los siguientes hallazgos:

### Con respecto a la colección "records"
* userIdBm no es requerido y no se valida su existencia en la creación de un registro, pero sí es requerido reportedUserIdBm en el reporte de un registro. No debería ser requerido userIdBm para la creación de un registro?
* Los siguientes campos no se están usando en consultas de la colección (ni siquiera como proyección), pero están definidos en el modelo.
  - continent
  - country
  - demAltitude
  - interpretedElevation
  - colection
  - earliestDateCollected
  - correctCountry
  - correctStateProvince
  - correctCounty
  - hasLocality
  - suggestedCountry
  - suggestedMunicipality
  - coordinateUncertaintyInMeters
  - lowUncertainty
  - altitudinalOutlier
  - consistentAltitude
  - diferenceInAltitude
  - insideKnownDistribution
  - dist2KnowRange
  - privateData
  - origin
* Estos campos no están ni siquiera en código viejo que no se está usando:
  - maximumElevationInMeters
  - minimumElevationInMeters
  - presence
  - recordStatus
  - season
  - externallyCreated

### Con respecto a la colección "species"
* Los siguientes campos no se están usando en consultas de la colección (ni siquiera como proyección), pero están definidos en el modelo.
  - migratoryType
  - taxVerifSource
  - nameAccordingTo
  - scientificNameAuthorship
  - iucnSpeciesID
* Estos campos están como requeridos en el modelo pero no se usan en ninguna consulta
  - genus
  - cites
  - specificEpithet
  - validName
  - speciesInCountry
  - sppInCol
  - recordsVisualizationPrivileges
  - uploadUser
  - uploadDate
  - genus
  - cites
  - specificEpithet
  - validName
  - speciesInCountry
  - sppInCol
  - recordsVisualizationPrivileges
  - uploadUser
  - uploadDate
  - genus
  - cites
  - specificEpithet
  - validName
  - speciesInCountry
  - sppInCol
  - recordsVisualizationPrivileges
  - uploadUser
  - uploadDate
  - genus
  - cites
  - specificEpithet
  - validName
  - speciesInCountry
  - sppInCol
  - recordsVisualizationPrivileges
  - uploadUser
  - uploadDate
  - genus
  - cites
  - specificEpithet
  - validName
  - speciesInCountry
  - sppInCol
  - recordsVisualizationPrivileges
  - uploadUser
  - uploadDate

### Con respecto a la colección "models"
* Notas sobre algunos campos:
  - modelLevel: no entiendo su uso en la función generalModelStats
  - modelStatus: no sé cómo puede afectar su no existencia en las agregaciones de la función generalModelStats
  - modelID: tener en cuenta que no es requerido
  - thresholdType: en la función read, si no existe clasificará en 'Thresholds'
  - gsLayer: si se va a seguirusando swagger, falta colocar este campo en la documentación de la función read
* Los siguientes campos no se están usando en consultas de la colección (ni siquiera como proyección), pero están definidos en el modelo.
  - omission
  - perfStatSD
  - pvalue (está dos veces en el schema!)
  - thresholdValue
  - userID_bm
  - wms
  - modelSeason
  - modelOrigin
  - modelGeoExtent
  - modelEpoch
* Estos campos no están ni siquiera en código viejo que no se está usando:
  - statForestLoss00min
  - statForestLoss00max
  - statForestLoss05min
  - statForestLoss05max
  - statForestLoss10min
  - statForestLoss10max
  - statForestLoss12min
  - statForestLoss12max
  - statForestLoss90min
  - statForestLoss90max
  - statForestLoss13min
  - statForestLoss13max
  - statForestLoss13
  - statForestLoss14min
  - statForestLoss14max
  - statForestLoss14
  - statForestLoss16min
  - statForestLoss16max
  - statForestLoss16
  - statForestSinInfo90
  - statForestSinInfo00
  - statForestSinInfo05
  - statForestSinInfo10
  - statForestSinInfo12
  - statForestSinInfo13
  - statForestSinInfo14
  - statForestSinInfo16
  - statForestAll90
  - statForestAll00
  - statForestAll05
  - statForestAll10
  - statForestAll12
  - statForestAll13
  - statForestAll14
  - statForestAll16
  - idRecords

**Comment by danflop** [comment]
Pendiente de reunión para decidir siguientes pasos.

**Comment by erikasv** [comment]
Se crearon las tareas [202](https://github.com/PEM-Humboldt/biomodelos_db_api/issues/202) y [203](https://github.com/PEM-Humboldt/biomodelos_db_api/issues/203) para hacer los ajustes necesarios encontrados en esta tarea
