### ISSUE TITLE
Instalar servidor geoserver

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/biomodelos_db_api#42]
Como desarrollador de BioModelos quiero montar un servidor para rasters de BioModelos (BioGeoServer) en máquina NoSQL 192.168.11.105 usando volumen NFS

**Comment by valegrajales** [comment]
Criterio de aceptación: Servidor de geoserver para biomodelos disponible para consulta en la máquina 192.168.11.105 con la documentación respectiva en repositorio gitlab.

**Comment by danflop** [comment]
Este proceso se detuvo en su momento y fue continuado después con otros objetivos. Los issues relacionados a estas nuevas actividades se pueden encontrar en este repositorio.
