### ISSUE TITLE
Revisar si se utiliza compresión de datos en API

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos_db_api#43]
Revisar si se utiliza compresión de datos en API

**Comment by danflop** [comment]
Criterio de aceptación: las respuestas del API deben retornar con compresión de datos para mejorar su desempeño.

**Comment by erikasv** [comment]
@danflop Se hace uso de la librería [compression](https://www.npmjs.com/package/compression/v/1.7.1) con todas las opciones por defecto (que creo que significa que intente comprimir todas las respuestas, excepto si tienen el header `Cache-Control` con `no-transform`)
